inherit_from: .rails-rubocop.yml

AllCops:
  Exclude:
    - 'lib/slider_block.rb'
    - 'lib/slider_block/**/*'

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
